### ISSUE TITLE
No link to this repo on npmjs.org

### ISSUE THREAD

**Issue by jwanglof** [dcgauld/starwars#2]
Hi!

I was about to use this library for the fun of it and found it on npmjs.org, but there's no link to this repo in the package which made me feel a bit unsafe since I couldn't verify the source code so there wasn't anything malicious in it.

Think it would be a great idea to add this repo-link to your npmjs.org package: https://www.npmjs.com/package/starwars :) 

Great job!

**Comment by dcgauld** [comment]
Thanks! Fixed in e58e40516f4b3636ab4fd89cd794f2ac33d0a54e.
